// <auto-generated />
using System;
using BlazorServerNoteApp_MarketNotes.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorServerNoteApp_MarketNotes.Data.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20220109030855_First Migrations")]
    partial class FirstMigrations
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.1");

            modelBuilder.Entity("BlazorServerNoteApp_MarketNotes.Model.MarketNote", b =>
                {
                    b.Property<int>("RID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryPath")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("PubDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Remark")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Topic")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("URL")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("RID");

                    b.ToTable("Notes");

                    b.HasData(
                        new
                        {
                            RID = -1,
                            Author = "",
                            Category = "",
                            CategoryPath = "",
                            Channel = "",
                            Content = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            Description = "Many apps today are just static files on the front end - HTML and JavaScript",
                            EventDate = new DateTime(2022, 1, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            PubDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "",
                            Tags = "",
                            Title = "Blazor WebAssembly on Azure Static Web Apps - Scott Hanselman's Blog",
                            Topic = "",
                            URL = "https://www.hanselman.com/blog/blazor-webassembly-on-azure-static-web-apps",
                            UserName = ""
                        },
                        new
                        {
                            RID = -2,
                            Author = "",
                            Category = "",
                            CategoryPath = "",
                            Channel = "",
                            Content = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            Description = "Polestar will spend the next three years executing a lofty electric vehicle launch schedule that will culminate with the Precept concept.",
                            EventDate = new DateTime(2022, 1, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            PubDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "",
                            Tags = "",
                            Title = "The Polestar Precept is a cypher for the EV automaker",
                            Topic = "",
                            URL = "https://techcrunch.com/2021/12/04/the-polestar-precept-is-a-cypher-for-the-ev-automakers-future/",
                            UserName = ""
                        },
                        new
                        {
                            RID = -3,
                            Author = "",
                            Category = "",
                            CategoryPath = "",
                            Channel = "",
                            Content = "",
                            CreatedAt = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = "",
                            Description = " 聯準會不加息？三不，一沒有",
                            EventDate = new DateTime(2022, 1, 9, 0, 0, 0, 0, DateTimeKind.Local),
                            PubDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Remark = "",
                            Tags = "",
                            Title = "美CPI創40年新高？週四聯準會FED升不升息？聯準會的三不一沒有 20211213《楊世光在金錢爆》第2769集",
                            Topic = "",
                            URL = "https://www.youtube.com/watch?v=lfVMCJ-H3hE",
                            UserName = ""
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
